#!/bin/sh
pairinguser="pairing@mumble.ugent.be"

set -e

for COMMAND in abduco socat ssh; do
	if ! command -v $COMMAND > /dev/null 2>&1; then
		printf '%s found: no\n' "$COMMAND"
		exit
	fi
done

if ! printf '%s' "$1" | grep '^[a-z0-9-]\+$'; then
	echo 'Please provide an alphanumeric (and -) session name'
	exit 1
fi

# Create a temporary directory for our sockets
umask 077
socketdir="$(mktemp -d)"
trap "rm -rf '$socketdir'" EXIT

# Connect a remote socket to a local socket
socat exec:"ssh -M '$pairinguser' 'guest $1'" unix-listen:"$socketdir/abduco",fork,reuseaddr,unlink-early &
socatpid="$!"

# Give socat some time to initialize
sleep 1

# Connect to the local socket
abduco -a "$socketdir/abduco"

# Cleanup
kill "$socatpid"
wait
