#!/bin/sh
set -e

session="$(uuidgen)"

socket="$(mktemp)"
rm "$socket"
SESSION_NAME="$session" SESSION_SOCKET="$socket" abduco -n "$socket"

echo "Session ID (copy this): $session"
sleep 5

socat unix:"$socket" exec:"ssh -M pairing@mumble.ugent.be 'host $session'" &
socatpid="$!"

read -p 'Press enter to start...' unused

abduco -a "$socket"

kill "$socatpid"
wait
