#!/bin/sh
SERVER="${SERVER:-mumble.ugent.be}"
shift # initial -c

set -e

socketdir=/tmp/pairing

errpf() {
	printf "$@" >&2
}

session_to_socket() {
	if printf '%s' "$1" | grep -q '^\(host\|guest\) [a-z0-9-]\+$'; then
		mkdir -p "$socketdir"
		printf '%s/%s' "$socketdir" "${1##* }"
	else
		errpf 'Please provide provide an alphanumeric (and -) session name.\n'
		exit 1
	fi
}

case "$1" in
host*)
	socket="$(session_to_socket "$1")"
	trap "rm '$socket'" EXIT KILL
	if [ -e "$socket" ]; then
		errpf 'Duplicate session name, use another or be the guest.\n'
		exit 1
	else
		socat - unix-listen:"$socket",fork,reuseaddr,unlink-early
	fi
	;;
guest*)
	socket="$(session_to_socket "$1")"
	trap "rm '$socket'" EXIT KILL
	if [ -e "$socket" ]; then
		socat unix:"$socket" -
	else
		errpf 'Session %s does not exist.\n' "$socket"
		exit 1
	fi
	;;
*)
	errpf '%s\n' "$1"
	errpf 'USAGE:\n'
	errpf '    ssh pairing@$SERVER host <session-name>\n'
	errpf '    ssh pairing@$SERVER guest <session-name>\n'
	exit 1
	;;
esac
